= Epic Online Services extension for Ren'Py
:nofooter:
:source-highlighter: rouge

https://ayowel.itch.io/renpy-epic-integration[image:https://img.shields.io/badge/itch.io-Free-limegreen[]]
https://github.com/Ayowel/renpy-epicgames-eos/releases/latest[image:https://shields.io/github/v/release/ayowel/renpy-epicgames-eos?label=latest-version[]]
https://www.apache.org/licenses/LICENSE-2.0.html[image:https://shields.io/github/license/ayowel/renpy-epicgames-eos?color=red[]]
https://github.com/Ayowel/renpy-epicgames-eos/issues[image:https://shields.io/github/issues/ayowel/renpy-epicgames-eos?color=orange[]]
https://dev.epicgames.com/en-US/sdk[image:https://img.shields.io/badge/EOS SDK-1.16.1-lightblue[]]

This extension adds Epic Games achievements support to Ren'Py. Ensure that you have accepted the usage conditions for the https://dev.epicgames.com/portal/en-US/home/sdk-download[Epic Games SDK] on the Epic Games Dev Portal before using this extension.

This extension only supports Ren'Py 8 and later.

Need to access the Epic Games API to do more ? The full API is mapped and available in Ren'Py under `epicapi.native`.

== Installation

[start]
. Download the https://github.com/Ayowel/renpy-epicgames-eos/releases/latest[latest release] (The file's name is `epic_eos.zip`)
. Unpack the release archive in your game's directory
. Create a new `game/epic.rpy` file with the following information:

[source, py]
--
# Get all attribute values under "Product Settings" -> "SDK Download & Credentials" at dev.epicgames.com
# You may need to create an EOS client for your game in "Product Settings" -> "Clients"
define config.epic_product = '0123456789abcdef0123456789abcdef'
define config.epic_client = 'AbCdEfGhIjKlMnOpQrStUv0123456789'
define config.epic_clientsecret = 'OT60Kvx3QM0ivZTncg8+yypmnNC1bcawfmQQ5C+8AGX'
# Game Deployment ID, may be overwritten by epic when running from the store
define config.epic_deployment = '456789abcdef0123456789abcdef0123'

# The client's policy should have the following Achievements features:
# findAchievementsForLocalUser, unlockAchievementForLocalUser,
# findAchievementDefinitions, readAchievementDefinition
#
# The client's policy should have the following Stats features to use stats:
# findStatsForLocalUser, ingestForLocalUser,
# findStats, readStats
define config.enable_epic_achievements = True

# The requested permissions. See EOS_EAuthScopeFlags for potential value
define config.epic_scopes = 0x0

init -1499 python:
    achievement.backends.insert(0, epicapi.EpicBackend())
--

[start=4]
. If using **Ren'py 8.0.X**, start epic at the start of your `splashscreen` label:

[source, py]
--
label splashscreen:
    if 'epicapi' in globals():
        $ epicapi.init()
    return
--

[start=5]
. Add the library files to your packaging rules file (usually `game/options.rpy`):

[source, py]
--
init python:
    ## Epic support, none of those files may be in an archive
    # Epic extension
    build.classify('game/epic_eos.rpe', 'linux mac windows')
    # Epic libs
    build.classify('libs/EOSSDK-Win*-Shipping.dll', 'windows')
    build.classify('libs/*/xaudio2_9redist.dll', 'windows')
    build.classify('libs/libEOSSDK-Linux-Shipping.so', 'linux')
    build.classify('libs/libEOSSDK-Mac-Shipping.dylib', 'mac')
--

[start=6]
. Follow the https://github.com/Ayowel/renpy-epicgames-eos/wiki/Configure-your-game-in-the-Epic-Games-Dev[wiki's instructions] to configure your game in Epic's web interface

_Loading the Epic DLL on windows requires that the player has the https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist[Visual C++ Redistributable] installed._

== Epic SDK game development

When developing with the EOS SDK, additional downloads are required to ensure that your game behaves as expected:

* Download the EOS SDK on the Epic Games Portal
* Extract the Epic Games EOS SDK dev Authentication tool from the SDK (under `SDK/Tools/EOS_DevAuthTool-*.zip` in the archive)
* Run the authentication tool
* Configure a port when prompted (if in doubt, set it to `6547`)
* Authenticate with a valid account in the authentication tool and set its key (if in doubt, set it to `username_key`)
* Create a new `game/01epic_dev.rpy` in your game with the following content (edit it if you did not use the recommend values before):

[source, py]
-- 
define config.epic_sandbox = 'abcdef0123456789abcdef0123456789' # Game Sandbox ID, provided by epic when running from the store
define config.epic_userlogin = 'localhost:6547' # Dev auth tool address:port
define config.epic_userpassword = 'username_key' # The username key configured in the dev auth tool
define config.epic_authtype = 'developer' # Enable dev auth tool usage
#define config.epic_report_achievements_status = False # Do not use Epic when checking achievement status

init python:
    # Remove dev file from release
    build.classify('game/01epic_dev.rpy', None)
    build.classify('game/01epic_dev.rpyc', None)
--

* Run the game you're developping

Note that the authentication tool should always be running and configured during development or your game won't be able to connect.
